### ISSUE TITLE
Let's use unicode characters for drawing

### ISSUE THREAD

**Issue by krassowski** [kn-bibs/dotplot#12]
@pjanek @bartma11 and rest of drawer team:
Maybe we can (beside basic ASCII characters) use special Unicode characters (https://en.wikipedia.org/wiki/Box-drawing_character) that are cross-platform (section DOS?) and produce nice-looking effects. There could be also a switch (an argument for argparse) so user can use ASCII as fallback in case of really odd and old terminal. Do you agree?

**Comment by pjanek** [comment]
Done!
