### ISSUE TITLE
We need to be able to download sequences from various databases

### ISSUE THREAD

**Issue by mehrfachflucht** [kn-bibs/dotplot#23]
Databases we are currently interested in are: NCBI (APIs: https://www.ncbi.nlm.nih.gov/home/develop/api.shtml), Uniprot (http://www.uniprot.org/help/programmatic_access#retrieving_individual_entries), Ensembl (BioMart) (API: http://rest.ensembl.org/)

**Comment by krassowski** [comment]
@kinga322 what is the current progress of this feature? Is that ready? Do you have a running example?

**Comment by kinga322** [comment]
We have working functions from_uniprot and from_ensemble on branch sequence. I am still working on downloading a sequence from NCBI, when this function is OK, I will make a pull request.
